name: rpncalc
version: '3.2.4'
summary: The command line Reverse Polish Notation (RPN) calculator
description: |
  RPNCalc is an easy to use command line based Reverse Polish
  Notation (RPN) calculator.

grade: stable
confinement: strict
base: core18

# Enable faster LZO compression
compression: lzo

apps:
  rpncalc:
    command: bin/java -Djava.util.prefs.userRoot="$SNAP_USER_DATA" -jar $SNAP/jar/rpncalc.jar

    plugs:
      - network

parts:
  library:
    plugin: maven
    source: https://github.com/frossm/library.git
    source-type: git
    source-tag: 'v2021.10.24'
    maven-options: [install]

  rpncalc:
    plugin: maven
    source: https://github.com/frossm/rpncalc.git
    source-branch: master
    source-type: git
    after: [library]
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
