name: rpncalc
version: '2.8.0'
summary: The command line Reverse Polish Notation (RPN) calculator
description: |
  RPNCalc is an easy to use command line based Reverse Polish
  Notation (RPN) calculator.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict  # use 'strict' once you have the right plugs and slots
base: core18

# Enable faster LZO compression
compression: lzo

apps:
  rpncalc:
    command: bin/java -Djava.util.prefs.userRoot="$SNAP_USER_DATA" -jar $SNAP/jar/rpncalc.jar

parts:
  library:
    plugin: maven
    source: https://github.com/frossm/library.git
    source-type: git
    source-tag: 'v2021.07.21'
    maven-options: [install]

  rpncalc:
    plugin: maven
    source: https://github.com/frossm/rpncalc.git
    source-branch: master
    source-type: git
    after: [library]

plugs:
   rpncalc-network:
      interface: network