name: rpncalc
version: '3.2.6'
summary: The command line Reverse Polish Notation (RPN) calculator
description: |
  RPNCalc is an easy to use command line based Reverse Polish
  Notation (RPN) calculator.
  
  RPNCalc is the command-line based Reverse Polish Notation (RPN) calculator.
  RPN calculators make it very simple to do complex calculations, especially
  if there are parentheses involved or order of operations is imporant.
  
  For a quick summary of usage, run the program with the -h switch or head
  over to the homepage for detailed usage instructions.
  
  Homepage: https://github.com/frossm/rpncalc

grade: stable
confinement: strict
base: core18

title: RPNCalc
website: https://github.com/frossm/rpncalc
contact: rpncalc@fross.org
issues: https://github.com/frossm/rpncalc/issues
icon: graphics/PostIt-512x512.png
license: MIT


# Enable faster LZO compression
compression: lzo

apps:
  rpncalc:
    command: bin/java -Djava.util.prefs.userRoot="$SNAP_USER_DATA" -jar $SNAP/jar/rpncalc.jar

    plugs:
      - network

parts:
  library:
    plugin: maven
    source: https://github.com/frossm/library.git
    source-type: git
    source-tag: 'v2021.10.24'
    maven-options: [install]

  rpncalc:
    plugin: maven
    source: https://github.com/frossm/rpncalc.git
    source-branch: master
    source-type: git
    after: [library]
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
